[package]
name = "pulldown-cmark-babelmark"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2021"

[dependencies]
rocket = { version = "=0.5.0-rc.2", features = ["json"] }

[dependencies.pulldown-cmark]
version = "=0.9.1" # Update version in main.rs when changing
default-features = false
features = ["simd"]
