[package]
name = "pulldown-cmark-babelmark"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }

[dependencies.pulldown-cmark]
version = "=0.8.0" # Update version in main.rs when changing
default-features = false
features = ["simd"]
