[package]
name = "pulldown-cmark-babelmark"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"

[dependencies]
env_logger = "0.6.1"
serde = { version = "1.0.90", features = ["derive"] }
tokio = { version = "0.2.13", features = ["macros", "rt-threaded"] }
warp = { version = "0.2.2", default-features = false }

[dependencies.pulldown-cmark]
version = "=0.8.0" # Update version in main.rs when changing
default-features = false
features = ["simd"]
